name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk \
          git build-essential libffi-dev libssl-dev \
          python3-setuptools python3-wheel

      - name: Install Buildozer
        run: |
          pip3 install --user buildozer cython

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
